### ISSUE TITLE
Syntax error when installing with opam

### ISSUE THREAD

**Issue by nathan-koskas** [coq-community/corn#57] opened 2018-07-18 22:10 UTC
I am on Ubuntu 18.04, and I use opam  2.0.0~rc and coq 8.8.1.
This message was found in the middle of the output:
```
File "./stdlib_omissions/Q.v", line 51, characters 45-46:
Error:
Syntax error: [constr:operconstr level 200] expected after '(' (in [constr:operconstr]).

Makefile:656: recipe for target 'stdlib_omissions/Q.vo' failed
make[1]: *** [stdlib_omissions/Q.vo] Error 1
make[1]: *** Waiting for unfinished jobs....
```
I have the same error when I use a fresh opam installation.

**Comment by spitters** [comment] 2018-07-20 05:17
@nathan-koskas Thanks for reporting this.
The CI passed very recently, https://github.com/c-corn/corn/pull/55 ,
although it may have been on 8.8.0.
@maximedenes Do you recall what version that was on?

**Comment by spitters** [comment] 2018-07-20 05:19
If I read this well, Travis uses the latest stable Coq version:
https://github.com/c-corn/corn/blob/master/.travis.yml

**Comment by Widly** [comment] 2018-09-12 14:57
I have same problem. How to resolve this?

**Comment by spitters** [comment] 2018-09-12 20:45
@Zimmi48 Am I mistaken in thinking that this kind of regression should be caught by
https://ci.inria.fr/coq/job/bench-corn/lastSuccessfulBuild/

**Comment by Zimmi48** [comment] 2018-09-13 08:43
@spitters Hum, I'm not quite sure because I never really understood these Jenkins tests very well.
In any case, I'll have a look at this issue next week and try to give a diagnosis.

**Comment by spitters** [comment] 2018-09-13 15:58
Thanks! Is there currently another CI-system for Coq.

**Comment by Zimmi48** [comment] 2018-09-13 22:26
Yes, documented here: https://github.com/coq/coq/tree/master/dev/ci#continuous-integration-for-the-coq-proof-assistant
That's the one that matters in practice.

**Comment by spitters** [comment] 2018-09-14 08:12
I must be overlooking something. Is the current CI for corn publicly
available? The only thing I could find was Jenkins.

**Comment by Zimmi48** [comment] 2018-09-14 08:27
Here is the latest build for master: https://gitlab.com/coq/coq/-/jobs/97439031
and the latest build for v8.8: https://gitlab.com/coq/coq/-/jobs/97530408
It's called formal-topology because https://github.com/bmsherman/topology is a library that depends o corn.
Note that this CI does not depend on OPAM.

**Comment by Zimmi48** [comment] 2018-09-19 17:18
@spitters The problem is pretty trivial: it's just that the last released version is not compatible anymore with Coq 8.8. Can you make a new tag? In the meantime, I'll change the version constraints of the 1.2.0 package.

**Comment by spitters** [comment] 2018-09-20 09:04
I pushed it here. For some reason, github does not want me to push that to the coq-community by a pull request. Is there a better way?
https://github.com/spitters/corn/tree/8.8.1

**Comment by Zimmi48** [comment] 2018-09-20 09:14
Yes, tags must be pushed directly.
The way I personally handle things is to define two remotes, one `upstream` for the official repo, and one `origin` for my fork.

```
$ git remote -v
origin	git@github.com:Zimmi48/math-classes (fetch)
origin	git@github.com:Zimmi48/math-classes (push)
upstream	git@github.com:coq-community/math-classes (fetch)
upstream	git@github.com:coq-community/math-classes (push)
```

My `.gitconfig` contains the following which makes `git push` push to my fork to a branch of the same name by default:
```
[push]
        default = current
[remote]
        pushdefault = origin
```

BTW, your 8.8.1 tag does not correspond to your latest commit. So I suggest to delete it (`git tag -d 8.8.1 && git push origin --delete 8.8.1`) before creating it again.
so when I want to push upstream I do `git push upstream`. In particular, `git push upstream --tags` when pushing tags.

**Comment by spitters** [comment] 2018-09-20 09:38
I hope I got it right now. The tag is there.

**Comment by Zimmi48** [comment] 2018-09-20 09:57
Yep. I updated coq/opam-coq-archive#414 with the new release.

**Comment by Zimmi48** [comment] 2018-09-21 19:35
Should be fixed now.

**Closed by Zimmi48** 2018-09-21 19:35 UTC

**Comment by Widly** [comment] 2018-09-22 10:54
Yes, it works, thanks!
